# Generated by Django 5.2.3 on 2025-07-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_module", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
