# Generated by Django 5.2.3 on 2025-06-29 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0004_profile_avatar'),
        ('blog_module', '0002_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account_module.profile'),
        ),
    ]
