CREATE TABLE "User" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" email,
  "password" password,
  "updated_date" datetime,
  "created_at" datetime
);

CREATE TABLE "Profile" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user" int,
  "first_name" varchar,
  "last_name" varchar,
  "image" file,
  "description" text,
  "created_at" datetime,
  "updated_date" datetime
);

CREATE TABLE "Post" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "image" file,
  "author" int,
  "title" varchar,
  "content" text,
  "category" int,
  "status" boolean,
  "created_at" datetime,
  "updated_date" datetime,
  "published_date" datetime
);

CREATE TABLE "category" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

ALTER TABLE "Post" ADD FOREIGN KEY ("category") REFERENCES "category" ("id");

ALTER TABLE "User" ADD FOREIGN KEY ("id") REFERENCES "Profile" ("user");

ALTER TABLE "Profile" ADD FOREIGN KEY ("id") REFERENCES "Post" ("author");
